# Yarn settings reference: https://yarnpkg.com/configuration/yarnrc

# Double-checks lockfile entries with the registry to detect tampering
# on untrusted branches.
enableHardenedMode: true

# Installs dependencies using a classic node_modules tree for maximal
# ecosystem compatibility.
nodeLinker: node-modules

# Keeps third-party postinstall scripts from running to reduce arbitrary
# execution risk.
enableScripts: false

# Opts out of Yarn's anonymous usage metrics so nothing gets reported upstream.
enableTelemetry: false

# Ignores npm releases that are less than three days old to avoid depending
# on freshly published packages.
npmMinimalAgeGate: "3d"
